# Utilities

_reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
_reference_os: &reference_os
  'linux'
_official_repo: &official_repo
  'Protelis/Protelis'

# Environment  

language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: xenial
addons:
  apt:
    packages:
    - graphviz
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="Protelis/Protelis"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@1.12"
    - JDK="adopt-openj9@1.12"
    # Disabled until gradle/gradle#8681 is solved, likely with Gradle 6+
#    - JDK="adopt@1.13"
#    - JDK="adopt-openj9@1.13"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - cd "$TRAVIS_BUILD_DIR"/protelis
        - ./gradlew clean check fatJar --scan --parallel
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        # Surge
        - secure: "z32+XowmfQf2x9UnfuXA1TxhnQlYDBoNkPTlHxsQBAj3bpt6GeFyJsDdx76BL/+iId2nPkO/aoDa1/gMar2TVMl0BZrmnsPr9Az+PLIQI2d+VvCfLw9DI1rb+7UFNc9KfBfBNJaU2soQdj/gWyf7M3AL5gCocZkgsZxKsqUbRv5zwz2dItqon5TcDzM3Mry1DiSN/E1QJ/YIxICfcgbi3qs9zXdlhCuWZHaBZ7ePW65TJATToxWqH2TnzhOD1UKT/FumTyvTXe33R+knqNdzHiL6GS2LkmT7oXnN7VYAIN5kfNDjv3JcMH6Gd4y+tkFwTERMuZoLyFu8/SPqlVlzc/UncChn3wWs2E9h1h1bxK/ClUQVIXsWFEuA5DLPgQ0P2t1N+2ypwarMWs+/tLkmR08Ol1rB8uObnx3VPu48vppAHwZyz8pnHVWEAK9wQlak84Y9Uplts1IAU7FQV6/2IQS3Oh/m0JR+quHL8td4elU6OGrMhWskS2D863wURe8Tmh9/a145LAK13kkXm4nIAiOj6QzJeWWDcz1fMRGReKRgYz+cG0dQ5PS7nZ0kNPJmcnN1GWYF5UZLJPaDe/ZzJS8s6FnpqwdpppPYE4trMzqgLYx64fwizI4sPWqYf9OB0E/cw1pHFAygsHiUsE45S/lnr4x3Ux0aeY6x/Os+ajg="
        - secure: "acaM42nAfxH9PqMa8DzptC9+0UP5CxIvhQW+FrTW3SkDDI2b4rdAmpOlg7dsaiuYXVwEwRKDwu+HmGayClC1JTeEjwXV6adH/2DPS7GwdZlxinX66PMxrOtJ8kfyuyr/LbTHNv4kvnVngGf7iyx9b9/7+1Yygs8znI71GNUY7SOg0nDVmk/aXZKWk3dg4OO3F1NEmwVDrWVHL+PIznZjpPiUZfmi+KJA+uJDAB6QnhBV78YlVi5FBG3NZG7V35ecFpIZ1w0Hqdst7QneRN4Sra3hJ22r8VJDWc4bcdVZ5dcXIOzTHIqeL9O4/oIOBHqgHjgIpYiXp93HSwoJD+PRXvF7JVXrebiIT6QT2+iLM7ph+Wj/suxTTsymhYI7iMBzRP0WDpsywBdx+LR7oBpoa32/v6KxCkdzt0RslUeMtRBRTltzAl9Sh9zcbw3RQtyBEpwtLwKF6+zfSUulTCP/JNMOHtfoYIv7+ZvgjRHXe0Jt3Ad/1HbHDpth9udYiBb3O9/bBWYl/rqxUAwGIGR9+pWPOIfIumZptI12eIiYOU2KLJ5P3/KRe9zIjVmH426TRrC1L/CQs4+N8Rt0S6nS5mkJ/tumxitfpmh+A+lt14P9sKxud8TCZpfHfmD1YOWwQA25oa3Kj+pErV1zm/zlHuGdmUYoeOkHOIL3Ruyx+OY="
        # Bintray
        - secure: "I4+Yjiu5Y5khd4MzFtY5UP2P+L72wklqgZ4uDNhQ+RJeIgOmbKit0tluWda/KpFVEC9K+SuGLURtzsL9XnmiBRbPdOaB/a6cJPW4TUzmpxbyu4Zl2OlcqngVOBku7al+54cMergdXFK0eflXlDik/8RH0stOd79tPoyDerdfUhoy1Tbdi0F014UBhHM4YraB7Tcunchw4InjcEWBtLY7VZMyw1CCeajf9r7ucXRyUnSjAjvR7jPVKg4+yiCefkC45xR0sok0cHec/HjDw9HReV40PkBNmTSTT8qjWPgH118zzMWR38B7gVvOIvPG549939yHv/q94VIIKn0ZDFwtk2CtcyX4HD35QM/EmfBHboEq55ckmSuz3L48X+C78697+4lZ4aa7/30y8TJIEiDeuAmNtvXAvf7zio+3lZs5OpyEAbHlpvt8ggzutrG6o9EskfgJ8c5g3zLP3/Q8OtefqR3DWArNNMpYk6UpL7JEN8LekloCOofM1XZh21ucqss+k1MC5IG3o9sCIs9ToW3CX9Kf9LGtpYhbnQPCNw9BBUxuIaignXOODGdYxjMmDQyZ+s1+mJr2WxHmmMxyu+TBFh5H9few26JDNWxO4+C2Ql95qlL9zUiRQFWsR3eOAqzbshY0yhTju0vIrsxxqxK+gtXij9jnKAfjvD3/Ai3bnIQ="
        - secure: "hhegqLy8o3Q0SJXFX5fqnixwQyADBNv5NSotuXEFf3qsb1/0CvGu+0rFkP0z+Aq5p8amv71NTl7KHvcpGodpNl28HYjbsfg3wbszdJIJuyX6fGxxMdaegb++coSU6mav9Of7zKbeg+uoE/qkE/CpGeak5L872xM3TiS0mA4+Eer3hArHDHt5zAzsUkEkZCgiuMYhUXopYB7BX1N/c/E3Sj8fD2yryDa4mfs5kaXChAbi/k4A6+CsScaF+F7v1XKaoJRy2PgYw28V9AsHr5Y6DwBYyGloZUGAWAcc6qHZaJqcO2ltVSAT1duTOi6kEy7Mvxyv4buj3hhMbq1OpINukCSKfLwwj3+gQOiOCDAmMIJPm/mJzjMS+puMu0+5K3bCRq2IrjyGkP6ZOflINaF6Pi4djBpZp2+ksTSdO73hJYSu6PltXS/XTEEocQYxvFM4cXNy1clxvMFI0aoC0Ihc7GdVheDbO0A1bJ0y9bxGEb0fYrEH1RyDvzxV4mXZFG8x9M4+sKhyIU7Et4dGB9d/YQCVp00//POOdKeXSlXFR/6SOp4eRga/G6S3a6aBJDcO7maiwC4rt9r6fPotGZvYuFRbVG4U2XvhW65V5LY4UVniGz5nBNu/EksMg5ULBMp+1IhJ79cMjotzj+pNvUwpBml6CbNzSYGY1BUUrIVZy9E="
        # Signing
        - secure: "dOpyCg9+ne6YXlulreCWGIRToh0PkaprYioRSIOIYkACoVwBTA7YiCU+3QgXI8wfTKQu6L5DW6lGN01q/AbrRB8wZZ+P0dhC7qDn6CD17KokfJ9nXbRpz8TIJjaJRvNRb7sjq1E/Vb+o0AKtW+hPjMp/0LVjucR+JA7f13GxV+mwKHExZl0kWUrwAJ0mLXzNNKR8TWARannPkjoWcTzzMRShJcQmxsSDKttMSqy4iPBO5YALFGSFPQQ1ajvnZeIs9XxQjw43zX+MqJGPA35eVb4FrNSZKr1uSp4OcNhHHnMG9BlGeYV8wdkZSKhUmfwYbXlkIZMMKlBjE2xen/72OdYq0YSNPHyiDUGQUC60t9bQd4MjqgQzZwo/G8wQjFLqtTaxNBGdXMK81rvfXI+X90H7wGaGh1DGeDgEnGMYR6YKZIVXYhrG7Hxhfd31YD4R+NTHxIAOlIwzf4oViWr/Jj3vIijuHl8DarmArt0ncTNvlW4mSAT4Molhj5NmFsHC0/ZE7HUgbtr8nNxvI+NPATyMkAhiywKiEeWIKSoqViI7HKe6o9CQiwmSgSHIhCXjafpOhC6/Tw60ifDeeK8O0HVgJHU3u/7m1EMASuWn14jZhUdEtTQJBSCJ7kEBHyICT+zKfks0Q0IePb8fk8fo0SI2SVX27Jd7ExCZaMY4Yz8="
        # Central
        - secure: "GuxRNbKcav2eJczEW/AHWrUWuyqIfE/SCNvs28CR4+kTc0n94z+LFp80FHVm8oPxZ+KF7IaImwtcqiDtW8LfnvBSDY0hPHpzxBbPiYQv2dBRTtwtHlcqImFyqJmApqwPLQDEWP+IfLbTJ1IZJyWRtETauy6QbAMb4iVo5atf0XQ/D9P+20vkD22TH+XPE+V+aAxOCt/SRdTwYvHDcKSTWbpi9cCaG6Sw5TZshcg/ts0lVLkyT56lb0YuVWRY4Ncfe3S2yzJoEjeQ4MaqtbD1si8QpUgr4JetQx4hzeO/GdsFzBVfUhEex/LoxEpWLnHN25J1cLC0IyUE47pVz088mjtqMB104M6YenjOUIyK0/VPKp3XwFPqdm52XoiCAkLBD7ejSIUaXT1/mH+CUwETE+3uxGyyrK8N4JhwObXDEI5rcmcsERvJBRi/WY0Q6thYk3/4CT9s4ficBq1RYqhvIFKBSkgC22zW80OFpltQD9x5Lz9mdhyhylxye3d04NjmlGE6u2vEH4MB60MWacygNXi8+cq6JhzkZF2rX73zDQuDLGIXYOaq+ljuVgkWaXkblRy+swF6ON5Sl5gt5nb14chq+gVpv6qhWTghRrZP2I/5P1tuKp8I7WBwr+lsN/J/83V0jnoBZxxzKks8o8Jz6HbfKmgqW0chFDU3+HTfoQE="
        - secure: "ls13hgzQaiKH8VqXOBywdlgXSMSRPYNmdNaLp3mhcQef/q58zSvypa6jDPpVh3hgttIs4dBIf4blD3mLKkUesS7aevpgWbKIijsrG5lDn+KvfYu6lLT86kdhzPNaGvpa5V0QZ36E4GfIvQmAbKb8+YGy3Vnn6Epot4Zs9SLlFo1EQcXoJFhZzUErR378ctKDDY8Z1tCkSs9IfJTfCJq3a30LTexzvW6VOvE3zEb1PLAtWIVcRiKbUFIww3TY9p4S0GTRL62gT040Y17drmPctW98K77Ie2PvMI05vJmXqow9L3LoS2S5hPY6Q9hv16liF4cAOKJqCjv0AfoSYwrxVu1Uklo4d5C3q0Yq0ta2eEYUhfCQ3Wxcsc4CqHcQQz991/G7WMm41kxLxK7B0n3fXhOAsgKyaHDMRvJUSFPvD+8Kx/2juPOjKEnJ7cXI3uXk04gkZ3iILyIE0z6TCaZUmK16kM5/356Ib82ZZWzDr0rlxMHP//ZkXAZgACoL2WzbipK38mYeKyLFZgIZVJBb1ffHyxUfl6U1QIiOmJmbUK8Q8u5noCa8UZGnnrzKDfxRspstD1PyYon36fju9FAoM23Z74U4v2pfVZahyJutBfnnsFzxxiIvEzsM0TucQPY/2gorx31/6vrlcKl063sfqHAhujcEQl+NU7fVWug2xfc="
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_bb4bf1920124_key -iv $encrypted_bb4bf1920124_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
        - "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"
        - sudo apt-get install -y nodejs
        - sudo npm install --global surge
      script:
        - cd "$TRAVIS_BUILD_DIR"/protelis
        - ./gradlew generateProtelisDoc -x test --scan
        - ./gradlew javadoc buildDashboard projectReport fatJar -x test --scan
        - mkdir -p report
        - cp --parent */build/reports build/reports report -R
      after_success:
        - ./gradlew publishAll
before_install:
  - dig +short myip.opendns.com @resolver1.opendns.com || true
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - cd "$TRAVIS_BUILD_DIR"/protelis
  - ./gradlew clean test --parallel --scan
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: RbsjBbESCgf2L6eerGH+tdrne5zJDlmq/ttzFnBXeN2n726W3xk7w08tQQVDlL+d90RPSbqVUGHS/erB7y3kGVYkfj0/w21PMZSY42Tw4r57YExSywPTBN+LDi/Cfrj1Kqknqk6WGOCKXSPkmyYLFaj+/qel7QxNDXVn8VEDfh2k5AdZVhdJW8bqNHM3aF8XxfyXgzg+Wg9NXrEz6UcztES3PoWjlDGgspOUel7/UMmsNnlWkt0MC5Bv8t0PviHaThD7qjiJfiDxIc3KhvWQWokRhcUxJVTnR1pjzMAXEypjGZANOEqxsLi8HAGwUmjsJp4Xv4GnIolRQMGYDDqxNvQKMU2vjqfSTSsnKb6TAP+et3igaoxjc4oZd9caeOl/dye8pY5KdA+ao/i7+vyUfIqo/b+hbq/cbLNDU8b/H1o5AeaeNMrdmUTi/vzKkbF7iyv0d702kQoHTAOZWRUYMzCo41eZPQbIutjWj+7yqARDyQE6S0k/jBzI44+RT0b3bkwXXV9fEd/pdqpeCg9nphO9i5Q/sC6bXBdGN+mO0DqbioqE1r9t8hZ38nVK3DodJq1n/hENSl3P9kNU0TZ3HY3nlotECa9WuLoWWIDNQI+LmgeEu0Ibc7MrVcLTAurl+l8V/zdwSEKQ0j4w9FrNFhpElO9TQYb2m3ChXEcubxI=
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/protelis/build/libs/protelis-redist*.jar"
    on:
      repo: *official_repo
      tags: true
      condition: $PUBLISH = "true"
  - provider: surge
    skip_cleanup: true
    project: "./protelis/build/docs/javadoc/"
    domain: protelis-unstable-doc.surge.sh
    on:
      repo: *official_repo
      branch: develop
      condition: $PUBLISH = "true"
  - provider: surge
    skip_cleanup: true
    project: "./protelis/report"
    domain: protelis-unstable-reports.surge.sh
    on:
      repo: *official_repo
      branch: develop
      condition: $PUBLISH = "true"
  - provider: surge
    skip_cleanup: true
    project: "./protelis/protelis-lang/build/protelis-docs/"
    domain: protelis-lang-unstable-doc.surge.sh
    on:
      repo: *official_repo
      branch: develop
      condition: $PUBLISH = "true"
  - provider: surge
    skip_cleanup: true
    project: "./protelis/build/docs/javadoc/"
    domain: protelis-doc.surge.sh
    on:
      repo: *official_repo
      tags: true
      condition: $PUBLISH = "true"
  - provider: surge
    skip_cleanup: true
    project: "./protelis/report"
    domain: protelis-reports.surge.sh
    on:
      repo: *official_repo
      tags: true
      condition: $PUBLISH = "true"
  - provider: surge
    skip_cleanup: true
    project: "./protelis/protelis-lang/build/protelis-docs/"
    domain: protelis-lang-doc.surge.sh
    on:
      repo: *official_repo
      tags: true
      condition: $PUBLISH = "true"

notifications:
  email:
    recipients:
      - danilo.pianini@unibo.it
      - jakebeal@gmail.com
