[versions]
alchemist = "4.0.0"

[libraries]
alchemist-interfaces = { module = "it.unibo.alchemist:alchemist-interfaces", version.ref = "alchemist" }
alchemist-loading = { module = "it.unibo.alchemist:alchemist-loading", version.ref = "alchemist" }
asm = "org.ow2.asm:asm:9.9.1"
commons-codec = "commons-codec:commons-codec:1.20.0"
commons-io = "commons-io:commons-io:2.21.0"
commons-lang = "org.apache.commons:commons-lang3:3.20.0"
commons-math = "org.apache.commons:commons-math3:3.6.1"
classgraph = "io.github.classgraph:classgraph:4.8.184"
guava = "com.google.guava:guava:33.5.0-jre"
junit = "junit:junit:4.13.2"
logback = "ch.qos.logback:logback-classic:1.5.22"
protelis-parser = "org.protelis:protelis.parser:12.6.0"
slf4j = "org.slf4j:slf4j-api:2.0.17"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.9.8"
trove4j = "net.sf.trove4j:trove4j:3.0.3"

[bundles]
alchemist = ["alchemist-interfaces", "alchemist-loading"]

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:7.0.8"
java-qa = "org.danilopianini.gradle-java-qa:1.156.0"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.3.0"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.97.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.2"
protelisdoc = "org.protelis.protelisdoc:3.0.121"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.8"
shadowJar = "com.gradleup.shadow:9.3.0"
taskTree = "com.dorongold.task-tree:4.0.1"
